schema_version: 1

context:
  name: net-http-persistent
  version: 4.0.4

package:
  name: rb-${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://rubygems.org/downloads/${{ name }}-${{ version }}.gem
    sha256: b62b7e528f72890f5cd67e7f687eeae55cf9f2cda22fd659494363da2fa7f4b2

build:
  number: 1
  noarch: generic
  script:
    - gem install -N -l -V --norc --ignore-dependencies ${{ name }}-${{ version }}.gem

requirements:
  host:
    - ruby >=2.7,<3
  run:
    - ruby >=2.7,<3
    - rb-connection_pool >=2.2,<3

tests:
  - script:
      - "ruby -r 'net/http/persistent' -e 'exit 0'"

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Thread-safe persistent connections with Net::HTTP
  homepage: https://rubygems.org/gems/${{ name }}
  repository: https://github.com/drbrain/${{ name }}
  documentation: https://www.rubydoc.info/gems/${{ name }}

extra:
  recipe-maintainers:
    - svengiegerich
    - janjagusch
